language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: OiR7Ix+VO7WSu7DNDBw8pDjfXulF41inib5DMjRQfsbUSQlhQ6D+vmN/e59UZ7m3vMsDqF/zwix+DoinQNOrrRfW35ICvbotz5bdQLMSnTiui3vzYzfUYXWGhq9cwVyI0JMP5pC8qQGLFcun4cC5HIfrFlDUiYus8WlmA5DqYzCNphEXKfAoNJExWpoKC42CTt/hnizeTBUn2o07VLejrWoYh+eOl04Uk99hDtB6SWlag3SFcEfuBlOYbRz9t0bJVOeKkjjoMWqc11zRLdf3uT3H7DKkXq7kG0/EvwSaZ0fWZUL6WaT1Cvh1we+eU7sydaLhN5m84YTzUx6FwlKmxDgcxOqqnrZFZv3CzsvWTRfy4628iQKfdDNm5pKhm0DsyZzKmHyiJUN6VR8lyDqELtuUFGoTZtLxnhd4cNQlT4/jpqllyRNZd7GWRWqUECkFc/Wtx5B39UExxYGkxckJ4cekTNRpQcfJpA8XhPgleXZmLLAzo6Ki2mZSWNauUgfC4PjfUTuu0p+rjBN0+U5N7E4s6uilPhVvDIzUhMLU39EZXbh1lBRDvM31nldkY9NQi2VjefJpG0EQ1ZTh7LYjWwkh7AR6k+OOo7QK0X8xEnNfPqXgoCReuDRv+lwWpcnU2XkJn3KJ5rHSFRwywHahXC0t0EYmuu2MHuqcN39APzk=
  - secure: PDq6Gd3TCt0KJ92gQ7dhJbFQ+k7F/H90UL83NUdF84xg74l4NYk+eqs9NdlNXUk9fdpeqRJXgV8X8fZZan18F3GS7CwklJM3s9c58LHFGNKwZEYkTCnABm/F6Z+oH4coMi+WrYqGpevzQKK2IQGnA5/2hL53zdlShWhBscZsMj9qIO9jLEf/deQxK1nSl8jP2A/cvmOy/BqBs6qxSfxelImJFSoEI9b62Rma78Cu7NXoIsWm6gImg+ygHBBWX/nPcG319vdc9KeFLtfBsPxQq7ZEvgza9UevpaXM2KyQKKKrOIFvQ6C8qVj8HcmT6l6xFryUDrpc+GuHvbM5vpv6riU6Zx1sNSPkgMNOuXr2eNq+ryK4kJxdUMitpzJNpQ0X4eNk4houg9h89Vwi3JbXZkk4Eht16vp7Pp6jLielze6HeXYj2o7bCvjSyJP6bMBUszylKWT2TIEtWpP/mXcurISI1UomuWNVrYiKFp/avw1bO73mUzWW+77NCsrDQ1gbn7uwMkziGYahxos7izYaTaUMZ4bXLHqk9dIjW0Ml8Bg8ZrRKj58M7zl/Sk58OXS4wTiWx6BQYkk265OptczcoOOd4Os+YrZjGLjw2MYaIL7Tv4E2w2jq0tcN+XmjJgEpdsFAAw5jWh+QmSTHYMnBElmcUsOK4KvuLrvJZEHuB9A=
